<?php

declare(strict_types=1);

return [
    'definitions' => [
        [
            'code' => 'registration_dashboard',
            'name' => 'Registration Dashboard',
            'description' => 'Betnabiso registration, completion and deposit-conversion performance.',
            'processor_identifier' => 'reports.registration_dashboard.v1.report.RegistrationDashboardReport',
            'template_identifier' => 'reports/registration_dashboard/v1/templates/dashboard.html',
            'definition_version' => '1.3.0',
            'calculation_version' => '1.3.0-provisional.1',
            'template_version' => '1.2.1',
            'reporting_period_type' => 'date_range',
            'supported_outputs' => ['pdf', 'png'],
            'is_active' => true,
            'display_order' => 10,
            'timeout_seconds' => 900,
            'retention_days' => 365,
            'allowed_roles' => ['admin', 'report_user'],
            'configuration' => [
                'excluded_dates_supported' => true,
                'include_report_date' => true,
                'registration_rules' => [
                    'completed_values' => ['completed', 'complete', 'verified', 'yes', 'true', '1'],
                    'duplicate_player_rule' => 'reject_generation',
                    'pending_validation_definition' => 'registration_not_completed',
                    'pending_values' => ['pending', 'unverified', 'incomplete'],
                    'exclude_deleted_accounts' => true,
                    'disabled_rate_denominator' => 'completed_registrations',
                    'deposited_excludes_disabled_accounts' => true,
                    'average_day_denominator' => 'included_calendar_days',
                    'clip_period_to_latest_registration_date' => true,
                    'provisional' => true,
                ],
                'rendering' => [
                    'pdf' => ['width' => 1536, 'height' => 1024],
                    'png' => ['width' => 1536, 'height' => 1024],
                ],
            ],
            'inputs' => [[
                'input_key' => 'user_list',
                'label' => 'User List Report',
                'description' => 'Upload the Betnabiso User List XLSX workbook or CSV file.',
                'is_required' => true,
                'accepted_extensions' => ['xlsx', 'csv'],
                'required_columns' => [
                    'player_id',
                    'username',
                    'registration_date',
                    'registration_completed',
                    'account_status',
                    'disabled_status',
                    'deleted_status',
                    'last_deposit_date',
                ],
                'validation_rules' => ['max_size_kb' => 51200, 'worksheet' => 'User List-28'],
                'display_order' => 10,
            ]],
        ],
        [
            'code' => 'deposits_withdrawals_bonus_dashboard',
            'name' => 'Deposits, Withdrawals and Bonus Dashboard',
            'description' => 'Production-style deposits, withdrawals, net cash flow and bonus reporting.',
            'processor_identifier' => 'reports.deposits_withdrawals_bonus_dashboard.v1.report.DepositsWithdrawalsBonusDashboardReport',
            'template_identifier' => 'reports/deposits_withdrawals_bonus_dashboard/v1/templates/dashboard.html',
            'definition_version' => '1.0.0-provisional.4',
            'calculation_version' => '1.0.0-provisional.4',
            'template_version' => '1.0.0-provisional.4',
            'reporting_period_type' => 'date_range',
            'supported_outputs' => ['pdf', 'png'],
            'is_active' => true,
            'display_order' => 20,
            'configuration' => [
                'excluded_dates_supported' => true,
                'payment_rules' => [
                    'summary_scope' => 'workbook_snapshot',
                    'published_deposit_adjustment_xaf' => 0,
                    'daily_deposit_adjustments_xaf' => [],
                    'audit_reference_deposit_total_xaf' => 2043435,
                    'audit_reference_daily_deposits_xaf' => ['2026-07-18' => 36550],
                    'provisional' => true,
                ],
                'rendering' => [
                    'pdf' => ['width' => 1536, 'height' => 1024],
                    'png' => ['width' => 1536, 'height' => 1024],
                ],
            ],
            'inputs' => [[
                'input_key' => 'payment_transactions',
                'label' => 'Deposits & Withdrawals report',
                'description' => 'Upload the original Deposits & Withdrawals XLSX workbook or CSV export.',
                'is_required' => true,
                'accepted_extensions' => ['xlsx', 'csv'],
                'required_columns' => [
                    'username', 'player_id', 'currency', 'amount', 'gateway',
                    'processed', 'transaction_type', 'transaction_date', 'status',
                ],
                'validation_rules' => [
                    'max_size_kb' => 51200,
                    'worksheet' => 'Deposits & Withdrawals-26',
                ],
                'display_order' => 10,
            ]],
        ],
        [
            'code' => 'cash_operations_dashboard',
            'name' => 'Cash Operations Dashboard',
            'description' => 'Sportsbook betting, winning payouts, GGR and margin operations.',
            'processor_identifier' => 'reports.cash_operations_dashboard.v1.report.CashOperationsDashboardReport',
            'template_identifier' => 'reports/cash_operations_dashboard/v1/templates/dashboard.html',
            'definition_version' => '1.0.0-provisional.3',
            'calculation_version' => '1.0.0-provisional.3',
            'template_version' => '1.0.0-provisional.3',
            'reporting_period_type' => 'date_range',
            'supported_outputs' => ['pdf', 'png'],
            'is_active' => true,
            'display_order' => 30,
            'configuration' => [
                'excluded_dates_supported' => true,
                'cash_operations_rules' => [
                    'valid_transaction_types' => ['Bet', 'Payout'],
                    'recognition_date' => 'Date & Time',
                    'status_handling' => 'not_present_in_source_export',
                    'provisional' => true,
                ],
            ],
            'inputs' => [[
                'input_key' => 'cash_operations',
                'label' => 'Cash Operations workbook',
                'description' => 'Upload the Cash Ops logs detailed XLSX workbook or CSV file.',
                'is_required' => true,
                'accepted_extensions' => ['xlsx', 'csv'],
                'required_columns' => [
                    'bet_id', 'transaction_date', 'currency', 'game', 'cash_amount',
                    'withholding_tax', 'transaction_type', 'player_id', 'username',
                ],
                'validation_rules' => ['max_size_kb' => 51200, 'worksheet' => 'Cash Ops logs detailed-15'],
                'display_order' => 10,
            ]],
        ],
        [
            'code' => 'player_activity_retention_dashboard',
            'name' => 'Player Activity and Retention Dashboard',
            'description' => 'Player journey, engagement, retention and mutually exclusive CRM segmentation.',
            'processor_identifier' => 'reports.player_activity_retention_dashboard.v1.report.PlayerActivityRetentionDashboardReport',
            'template_identifier' => 'reports/player_activity_retention_dashboard/v1/templates/dashboard.html',
            'definition_version' => '1.0.0-provisional.5',
            'calculation_version' => '1.0.0-provisional.5',
            'template_version' => '1.0.0-provisional.5',
            'reporting_period_type' => 'date_range',
            'supported_outputs' => ['pdf', 'png'],
            'is_active' => true,
            'display_order' => 40,
            'timeout_seconds' => 1200,
            'configuration' => [
                'excluded_dates_supported' => true,
                'player_activity_rules' => [
                    'betting_source' => 'bet_legs',
                    'settled_bet_statuses' => ['lost', 'won'],
                    'dormancy_days' => 30,
                    'registration_completed_values' => ['yes', 'completed', 'verified', 'true', '1'],
                    'successful_payment_statuses' => ['completed [approved]'],
                    'exclude_disabled_accounts' => true,
                    'exclude_deleted_accounts' => true,
                    'vip_percentile' => 0.01,
                    'value_basis' => 'lifetime_deposits',
                    'provisional' => true,
                ],
                'rendering' => [
                    'pdf' => ['width' => 1536, 'height' => 1024],
                    'png' => ['width' => 1536, 'height' => 1024],
                ],
            ],
            'inputs' => [
                [
                    'input_key' => 'user_list',
                    'label' => 'User List workbook',
                    'description' => 'Registration, verification and account-status XLSX or CSV source.',
                    'is_required' => true,
                    'accepted_extensions' => ['xlsx', 'csv'],
                    'required_columns' => ['player_id', 'username', 'registration_date', 'registration_completed', 'disabled_status', 'deleted_status'],
                    'validation_rules' => ['max_size_kb' => 51200, 'worksheet' => 'User List-28'],
                    'display_order' => 10,
                ],
                [
                    'input_key' => 'payment_transactions',
                    'label' => 'Deposits & Withdrawals workbook',
                    'description' => 'Successful deposits, withdrawals and first-deposit activity as XLSX or CSV.',
                    'is_required' => true,
                    'accepted_extensions' => ['xlsx', 'csv'],
                    'required_columns' => ['username', 'player_id', 'amount', 'gateway', 'processed', 'transaction_type', 'transaction_date', 'status'],
                    'validation_rules' => ['max_size_kb' => 51200, 'worksheet' => 'Deposits & Withdrawals-26'],
                    'display_order' => 20,
                ],
                [
                    'input_key' => 'bet_legs',
                    'label' => 'Bet Legs workbook',
                    'description' => 'Sports and casino betting activity as XLSX or CSV.',
                    'is_required' => true,
                    'accepted_extensions' => ['xlsx', 'csv'],
                    'required_columns' => ['bet_id', 'player_id', 'username', 'bet_date', 'game', 'slip_state', 'bet_status', 'stake'],
                    'validation_rules' => ['max_size_kb' => 51200, 'worksheet' => 'Bet Legs Report-6'],
                    'display_order' => 30,
                ],
            ],
        ],
        [
            'code' => 'overall_performance_dashboard',
            'name' => 'Overall Performance Dashboard',
            'description' => 'Executive consolidation of exact-period completed module results.',
            'processor_identifier' => 'reports.overall_performance_dashboard.v1.report.OverallPerformanceDashboardReport',
            'template_identifier' => 'reports/overall_performance_dashboard/v1/templates/dashboard.html',
            'definition_version' => '1.0.0-provisional.4',
            'calculation_version' => '1.0.0-provisional.4',
            'template_version' => '1.0.0-provisional.4',
            'reporting_period_type' => 'date_range',
            'supported_outputs' => ['pdf', 'png'],
            'is_active' => true,
            'display_order' => 50,
            'timeout_seconds' => 900,
            'configuration' => [
                'excluded_dates_supported' => true,
                'overall_rules' => [
                    'source_selection' => 'explicit_generation_ids_exact_period',
                    'reconciliation_policy' => 'strict_fail_before_publication',
                    'decimal_tolerance' => 0.01,
                    'bonus_unavailable_display' => 'Unavailable',
                    'provisional' => true,
                ],
            ],
            'inputs' => [],
        ],
    ],
];
